# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            浮落客
tagline:          '开放的群组博客'
description:      '一个简单的群组博客，我们追求独立和自由，我们与体制和框架做斗争'
url:              http://shelldone.com

author:
  name:           '远果果'
  url:            http://weibo.com/inkkxl

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/poole/lanyon
